### ISSUE TITLE
Schema hasn't been registered for model

### ISSUE THREAD

**Issue by pjl4** [codingdojo-mean-0219/plutz#3]
Both modularized Mongoose and 1955 API are throwing the same error,

MissingSchemaError: Schema hasn't been registered for model "Person".
Use mongoose.model(name, schema)
    at new MissingSchemaError (C:\Users\Peter\Desktop\mean-assignment-landscape-master\04-mongodb\05-api\01-1955-api\node_modules\mongoose\lib\error\missingSchema.js:22:11)
    at Mongoose.model (C:\Users\Peter\Desktop\mean-assignment-landscape-master\04-mongodb\05-api\01-1955-api\node_modules\mongoose\lib\index.js:434:13)
    at Object.<anonymous> (C:\Users\Peter\Desktop\mean-assignment-landscape-master\04-**mongodb\05-api\01-1955-api\server\controllers\users.js:1:97)**
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Peter\Desktop\mean-assignment-landscape-master\04-mongodb\05-api\01-1955-api\server\config\routes.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

 The bold statement happens inside the Controller with both apps, its the statement to require mongoose and the model, unsure why this happens because it should start the Model with the proper Use mongoose.model(name, schema) statement

**Comment by dojo-json** [comment]
Consider what you are exporting from your database config:

https://github.com/codingdojo-mean-0219/plutz/blob/844e09cbac8f5db7b543c1da09fe588653c59371/04-mongodb/05-api/01-1955-api/server/config/mongoose.js#L4-L14

And then how you are using that export after requiring. 

https://github.com/codingdojo-mean-0219/plutz/blob/844e09cbac8f5db7b543c1da09fe588653c59371/04-mongodb/05-api/01-1955-api/server.js#L7-L10

**Comment by pjl4** [comment]
Duh, it's a function.

Thanks!
